Merge changes from main into jenkins-3-0-0 (#131)
* Fix error on missing `ingress.paths` value (#114)

* Fix error on missing `ingress.paths` value

Signed-off-by: Max Bambasek <bambasek.max@gmail.com>

* Add unit test

Signed-off-by: Max Bambasek <bambasek.max@gmail.com>

* Add/document Tilt (#89)

* Add/document Tilt

This commit adds an easy development workflow with Tilt. Given a configured local k8s environment, Tilt will watch the helm chart and automatically re-deploy when there are changes. This speeds up development on the chart significantly.

Signed-off-by: Brandon High <highb@users.noreply.github.com>

* Override admin password for ease of use

Signed-off-by: Brandon High <highb@users.noreply.github.com>

* Password shouldn't be jenkins, Tilt redacts it all over the place making logs unreadable

Signed-off-by: Brandon High <highb@users.noreply.github.com>

* Password needs to be string

Signed-off-by: Brandon High <highb@users.noreply.github.com>

* Move Tiltfile to chart/jenkins, docs to CONTRIBUTING

Signed-off-by: Brandon High <highb@users.noreply.github.com>

* Enable scriptApproval for JCasC config (#105)

Signed-off-by: Fabrice Rabaute <fabrice@arista.com>

* Add a startup probe, if a cluster supports it.  (#119)

* Add a startup probe, if a cluster supports it.

Taken from https://github.com/helm/charts/issues/22279

Signed-off-by: Waldemar Zurowski <waldemar.zurowski@r3.com>

* Bumbed version number and updated changelog

Signed-off-by: Waldemar Zurowski <waldemar.zurowski@r3.com>

* Updated settings for startup probe

* do not delay startup probe
* increased failure treshold
* version bumped to 2.16.0

Signed-off-by: Waldemar Zurowski <waldemar.zurowski@r3.com>

* Updated CHANGELOG message

and fixed a typo in earlier message

Signed-off-by: Waldemar Zurowski <waldemar.zurowski@r3.com>

* template startup probe via values.yaml

Signed-off-by: Torsten Walter <mail@torstenwalter.de>

* Removed obsolete whitespaces

Signed-off-by: Waldemar Zurowski <waldemar.zurowski@r3.com>

Co-authored-by: Torsten Walter <mail@torstenwalter.de>

* Updated locations of stable and incubator Helm repositories (#125)

* Updated locations of stable and incubator Helm repositories

otherwise `Add dependency chart repos` step fails with following
message:

```
Error: repo "https://kubernetes-charts.storage.googleapis.com/" is no
longer available; try "https://charts.helm.sh/stable" instead
```

with a similar message for `incubator` repository

Signed-off-by: Waldemar Zurowski <waldemar.zurowski@r3.com>

* Removed `Add dependency chart repos`

Jenkins chart doesn't defined any dependencies anyway

Signed-off-by: Waldemar Zurowski <waldemar.zurowski@r3.com>

* Use helm 3.4.0 for release pipeline (#127)

Signed-off-by: Torsten Walter <mail@torstenwalter.de>

* Switch to using plugin manager (#117)

Once 2.1.1 is available in images, we can start using the plugin manager

Signed-off-by: Gavin Mogan <git@gavinmogan.com>

* Fix location of jenkins.war file. (#129)

It is located in `/usr/share/jenkins/jenkins.war` and can be configured via `master.jenkinsWar`.

Signed-off-by: Torsten Walter <mail@torstenwalter.de>

Co-authored-by: 11000100111000 <56624577+11000100111000@users.noreply.github.com>
Co-authored-by: Brandon High <highb@users.noreply.github.com>
Co-authored-by: Fabrice <jfr@core-services.fr>
Co-authored-by: Waldemar Żurowski <45210402+wzur-r3@users.noreply.github.com>
Co-authored-by: Gavin Mogan <github@gavinmogan.com>